name: SEBS
favicon: null
layout_spectrum: 0.6885047040414065
typography_spectrum: 0.7778413880150765
title: SEBS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#e7e7e7'
    - '#afafaf'
    - '#707070'
    - '#303030'
  brandStrength: 0.8125
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0.8989445476327091
purpose: []
