name: SEBS
favicon: null
layout_spectrum: 0.6885047040414065
typography_spectrum: 0.7778413880150765
title: SEBS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5009315533097833
  lightness: 0.9960641872603446
  saturation: 0.1578889675438404
  rhythmicContrast: 0.8989445476327091
purpose: []
